# Generated by Django 5.2.16 on 2026-07-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('phone_primary', models.CharField(max_length=15)),
                ('phone_secondary', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('working_days', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Profile',
                'verbose_name_plural': 'School Profile',
            },
        ),
    ]
