# Generated by Django 5.2.16 on 2026-10-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feestructure_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecollection',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Debit Card', 'Debit Card'), ('Bank Transfer', 'Bank Transfer')], max_length=30),
        ),
    ]
