# Generated by Django 5.2.16 on 2026-07-24 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_student_photo'),
        ('exams', '0002_studentresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='exam_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='exams.examsubject'),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.student'),
        ),
    ]
