# Generated by Django 5.2.16 on 2026-07-20 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('admission_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.academicyear')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.schoolclass')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.section')),
            ],
            options={
                'ordering': ['admission_number'],
            },
        ),
    ]
