# Generated by Django 5.2.16 on 2026-07-20 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_student'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='academics.academicyear')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='academics.schoolclass')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='staff.staff')),
            ],
            options={
                'ordering': ('school_class', 'section'),
                'unique_together': {('teacher', 'subject', 'school_class', 'section', 'academic_year')},
            },
        ),
    ]
